services:
  fmm-db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: theindiegrid
    ports:
      - "5432:5432"
    networks:
      - fmm-local
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  fmm-local:
    driver: bridge

volumes:
  db-data:
    driver: local
