services:
  fmm-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - fmm-local
    depends_on:
      - fmm-db
      - nginx
      - minio
    restart: always

  fmm-db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fmm
    ports:
      - "5432:5432"
    networks:
      - fmm-local
    volumes:
      - db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - fmm-local
    volumes:
      - minio-data:/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - fmm-local
    depends_on:
      - minio
    restart: always

networks:
  fmm-local:
    driver: bridge

volumes:
  db-data:
    driver: local
  minio-data:
    driver: local
  nginx-certs:
    driver: local
